[project]
name = "splunk-laughing-bassoon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "mcp>=1.27.2",
    "openai>=2.38.0",
    "requests>=2.34.2",
    "sentence-transformers>=5.5.1",
    "streamlit>=1.58.0",
    "urllib3>=2.7.0",
    "watchdog>=6.0.0",
]
